// Generated by CoffeeScript 1.6.3
(function() {
  var i, pr, _i;

  pr = $(".product-row");

  for (i = _i = 1; _i <= 2; i = ++_i) {
    pr.after(pr.html());
  }

  $(".product-alternate-images > img").on("click", function(e) {
    $("#detail-img").prop('src', e.target.src);
    if ("png" === e.target.src.slice(e.target.src.slice.length - 5)) {
      return $("#detail-img").addClass("img-drop-shadow");
    } else {
      return $("#detail-img").removeClass("img-drop-shadow");
    }
  });

}).call(this);
